<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="T_GetLastMsgLogger" Id="{cc23bc20-01af-46bf-8f0e-6dd882c31443}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_GetLastMsgLogger IMPLEMENTS I_Logger

VAR_OUTPUT
	lastLog : STRING;
	lasLogLevel : DWORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ToLog" Id="{e1ac84b0-4f69-4a30-a79b-953ef2b1eeab}">
      <Declaration><![CDATA[METHOD ToLog
VAR_INPUT
	Msg	: STRING(255);
	(* generic level, can be mapped to logging framework*)
	LogLevel	: DWORD;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[lastLog := MSg;
lasLogLevel := LogLevel;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="T_GetLastMsgLogger">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="T_GetLastMsgLogger.ToLog">
      <LineId Id="9" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>